spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reboto
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        default_schema: reboto
    hibernate:
      ddl-auto: validate
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations:
      - classpath:db/migration
    schemas:
      - reboto
    placeholder-replacement: false